# Generated by Django 5.1.1 on 2024-09-21 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carmodel',
            old_name='carMake',
            new_name='car_make',
        ),
    ]
